
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tudbtihblxsgxveanbtv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR1ZGJ0aWhibHhzZ3h2ZWFuYnR2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE3NDU1ODksImV4cCI6MjA1NzMyMTU4OX0.hRUW1xJskHPbjXQz4VezaRJ0yhcTt76bvYejL1ZvKaw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Define types for the tables we've created
export type Dish = {
  id: string;
  name: string;
  createdAt: string;
  cuisines: string[];
  source?: {
    type: 'url' | 'book' | 'none';
    value: string;
    page?: number;
    bookId?: string;
  };
  lastMade?: string;
  timesCooked: number;
  user_id: string;
};

export type MealHistory = {
  id: string;
  dishId: string;
  date: string;
  notes?: string;
  user_id: string;
};

export type Cookbook = {
  id: string;
  name: string;
  author?: string;
  description?: string;
  createdAt: string;
  user_id: string;
};
