
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tudbtihblxsgxveanbtv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR1ZGJ0aWhibHhzZ3h2ZWFuYnR2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE3NDU1ODksImV4cCI6MjA1NzMyMTU4OX0.hRUW1xJskHPbjXQz4VezaRJ0yhcTt76bvYejL1ZvKaw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Define types for the tables we've created
export type Dish = {
  id: string;
  name: string;
  createdAt: string;
  cuisines: string[];
  source?: {
    type: 'url' | 'book' | 'none';
    value: string;
    page?: number;
    bookId?: string;
  };
  lastMade?: string;
  timesCooked: number;
  user_id: string;
};

export type MealHistory = {
  id: string;
  dishId: string;
  date: string;
  notes?: string;
  user_id: string;
};

export type Cookbook = {
  id: string;
  name: string;
  author?: string;
  description?: string;
  createdAt: string;
  user_id: string;
};

// Mapping functions to convert between database and client formats
export const mapDishFromDB = (dish: Database['public']['Tables']['dishes']['Row']): Dish => ({
  id: dish.id,
  name: dish.name,
  createdAt: dish.createdat,
  cuisines: dish.cuisines,
  source: dish.source as any,
  lastMade: dish.lastmade || undefined,
  timesCooked: dish.timescooked,
  user_id: dish.user_id
});

export const mapDishToDB = (dish: Partial<Dish>): Partial<Database['public']['Tables']['dishes']['Insert']> => ({
  id: dish.id,
  name: dish.name,
  createdat: dish.createdAt,
  cuisines: dish.cuisines,
  source: dish.source as any,
  lastmade: dish.lastMade,
  timescooked: dish.timesCooked,
  user_id: dish.user_id
});

export const mapMealHistoryFromDB = (history: Database['public']['Tables']['meal_history']['Row']): MealHistory => ({
  id: history.id,
  dishId: history.dishid,
  date: history.date,
  notes: history.notes || undefined,
  user_id: history.user_id
});

export const mapMealHistoryToDB = (history: Partial<MealHistory>): Partial<Database['public']['Tables']['meal_history']['Insert']> => ({
  id: history.id,
  dishid: history.dishId,
  date: history.date,
  notes: history.notes,
  user_id: history.user_id
});

export const mapCookbookFromDB = (cookbook: Database['public']['Tables']['cookbooks']['Row']): Cookbook => ({
  id: cookbook.id,
  name: cookbook.name,
  author: cookbook.author || undefined,
  description: cookbook.description || undefined,
  createdAt: cookbook.createdat,
  user_id: cookbook.user_id
});

export const mapCookbookToDB = (cookbook: Partial<Cookbook>): Partial<Database['public']['Tables']['cookbooks']['Insert']> => ({
  id: cookbook.id,
  name: cookbook.name,
  author: cookbook.author,
  description: cookbook.description,
  createdat: cookbook.createdAt,
  user_id: cookbook.user_id
});
